[package]
name = "ireqwest"
version = "0.1.0"
authors = ["qiongtubao <810776886@qq.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = {version = "1.0", features=["derive"]}
serde_derive = "1.0"
serde_json = "1.0"
url = "*"