[package]
name = "hyper-client"
version = "0.1.0"
authors = ["qiongtubao <810776886@qq.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
serde = {version = "1.0", features=["derive"]}
serde_derive = "1.0"
serde_json = "1.0"
hyper-tls = "*"
futures = "*"
tokio = "*"